### PR TITLE
fix #151 Don't return deleted docs on qget

### LINKED ISSUE #151: FLUSHDB doesn't affect index
Index survives past `FLUSHDB` - this will be undesirable. 

Consider this:
```
$ launchctl start io.redis.redis-server
$ redis-cli
> keys *
(empty list or set)
> json.set user1 $ '{"last":"Joe", "first":"Mc"}' INDEX person
OK
> json.index add person last $.last
OK
> JSON.QGET person Jo*
"{\"user1\":[{\"last\":\"Joe\",\"first\":\"Mc\"}]}"
> flushdb
OK
> JSON.QGET person Jo*
"{\"user1\":[]}"
```

This will be a very unexpected outcome for most Redis users. `FLUSHDB` (or `FLUSHALL`) should remove all data and this type of behaviour could reveal information that could be sensitive. 

I assume that the indexes are behind held outside of keyspace, which I get to some degree, but this will be very strange to explain.

### PR DESCRIPTION
**Pull request by gkorland**
Copy from https://github.com/RedisJSON/RedisJSON2/pull/76/

### CODE REVIEW

File: src/commands/index.rs [hunk 1]
```diff
@@ -83,6 +83,13 @@ pub fn add_document(key: &str, index_name: &str, doc: &RedisJSON) -> RedisResult
     REDIS_OK
 }
 
+pub fn remove_document(key: &str, index_name: &str) -> RedisResult {
+    if let Some(schema) = schema_map::as_ref().get(index_name) {
```
Comment (gavrie) [inline src/commands/index.rs:87]: Please use the explicit `let map = schema_map::as_ref();` as in the other methods for consistency (and I also think it's more readable).

File: src/commands/index.rs [hunk 2]
```diff
@@ -170,9 +177,9 @@ fn scan_and_index(ctx: &Context, schema: &Schema, cursor: u64) -> Result<u64, Re
                             .get_value::<RedisJSON>(&REDIS_JSON_TYPE)
                             .and_then(|doc| {
                                 if let Some(data) = doc {
-                                    if let Some(index) = &data.index {
-                                        if schema.name == *index {
-                                            add_document(key, index, data)?;
+                                    if let Some(index) = &data.value_index {
+                                        if schema.name == index.index {
+                                            add_document(key, &index.index, data)?;
```
Comment (gavrie) [inline src/commands/index.rs:182]: Please rename the variable inside the pattern match for consistency:

```
if let Some(value_index) = &data.value_index {
    if schema.name == value_index.index {
        add_document(key, &value_index.index, data)?;
```

File: src/redisjson.rs [hunk 3]
```diff
@@ -62,10 +63,16 @@ impl Path {
     }
 }
 
+#[derive(Debug, Clone)]
+pub struct ValueIndex {
+    pub key: String,
+    pub index: String,
+}
```
Comment (gavrie) [inline src/redisjson.rs:70]: I suggest naming this field `index_name` and not `index`; there's too many things `index` can refer to already.

File: src/lib.rs [hunk 4]
```diff
@@ -98,7 +98,7 @@ fn json_set(ctx: &Context, args: Vec<String>) -> RedisResult {
 
     let mut format = Format::JSON;
     let mut set_option = SetOptions::None;
-    let mut index = None;
+    let mut value_index = None;
 
     loop {
```
Comment (gavrie) [inline src/lib.rs:103]: Not related to your change, but `cargo clippy` rightly suggests to simplify this `loop` with `while let`:

```
    while let Some(s) = args.next() {
        match s.to_uppercase().as_str() {
```

File: Cargo.toml [hunk 5]
```diff
@@ -14,4 +14,4 @@ serde_json = "1.0"
 libc = "0.2"
 jsonpath_lib = { git="https://github.com/gkorland/jsonpath.git", branch="patch-1" }
 redis-module = { version="0.7.0", features = ["experimental-api"]}
-redisearch_api = "0.3.0"
+redisearch_api =  { git="https://github.com/RediSearch/redisearch-api-rs", branch="del_doc"}
```
Comment (gavrie) [inline Cargo.toml:17]: After finishing your `redisearch_api` PR (and releasing) this should be updated to a new release.

File: src/commands/index.rs [hunk 6]
```diff
@@ -61,7 +61,7 @@ fn add_field(index_name: &str, field_name: &str, path: &str) -> RedisResult {
     if schema.fields.contains_key(field_name) {
         Err("Field already exists".into())
     } else {
-        schema.index.create_field(field_name);
+        schema.index.create_field(field_name, 1.0, None, false);
```
Comment (gavrie) [inline src/commands/index.rs:64]: We should fix the ambiguous arguments (per your redisearch_api PR).

File: src/commands/index.rs [hunk 7]
```diff
@@ -209,27 +216,34 @@ where
...
-                                        .map_err(|e| e.into()) // Convert Error to RedisError
-                                        .map(|values| {
-                                            values.into_iter().map(|val| val.clone()).collect()
-                                        })
+                        let redis_key = ctx.open_key(&key);
+                        if redis_key.is_null() {
+                            // remove doc that doesn't exist from index
+                            remove_document(&key, &index_name)?;
+                            Ok(acc)
+                        } else {
```
Comment (gavrie) [inline src/commands/index.rs:228]: Please explain when this can happen, if we remove it from the index when deleting. Is this for backwards compatibility?

File: src/redisjson.rs [hunk 8]
```diff
@@ -402,16 +412,22 @@ pub mod type_methods {
 
     #[allow(non_snake_case, unused)]
     pub unsafe extern "C" fn free(value: *mut c_void) {
-        Box::from_raw(value as *mut RedisJSON);
+        let json = value as *mut RedisJSON;
+        if let Some(index) = &(*json).value_index {
+            index::remove_document(&index.key, &index.index);
+        }
+
+        Box::from_raw(json);
```
Comment (gavrie) [inline src/redisjson.rs:420]: This code can be cleaned up a bit by boxing first instead of using the raw pointer (and adding a comment):
```
        let json = value as *mut RedisJSON;

        // Take ownership of the data from Redis (causing it to be dropped when we return)
        let json = Box::from_raw(json);

        if let Some(index) = &json.value_index {
            index::remove_document(&index.key, &index.index);
        }
```

File: src/commands/index.rs (hunk 1 above)
Comment (gkorland) [reply src/commands/index.rs:87]: :+1:

File: src/redisjson.rs (hunk 3 above)
Comment (gkorland) [reply src/redisjson.rs:70]: :+1:

File: src/lib.rs (hunk 4 above)
Comment (gkorland) [reply src/lib.rs:103]: :+1:

File: src/commands/index.rs (hunk 6 above)
Comment (gkorland) [reply src/commands/index.rs]: :+1:

File: src/redisjson.rs (hunk 8 above)
Comment (gkorland) [reply src/redisjson.rs:420]: :+1:

File: src/commands/index.rs (hunk 7 above)
Comment (gkorland) [reply src/commands/index.rs:228]: it was the original lazy solution, I think it can be removed now.

File: src/commands/index.rs (hunk 2 above)
Comment (gkorland) [reply src/commands/index.rs:182]: :+1:

File: src/lib.rs [hunk 9]
```diff
@@ -125,8 +124,8 @@ fn json_set(ctx: &Context, args: Vec<String>) -> RedisResult {
     match (current, set_option) {
         (Some(ref mut doc), ref op) => {
             if doc.set_value(&value, &path, op, format)? {
-                if let Some(index) = index {
-                    index::add_document(&key, &index, &doc)?;
+                if let Some(index) = value_index {
```
Comment (gavrie) [inline src/lib.rs:127]: For consistency this should be `if let Some(value_index) = value_index {`

File: src/lib.rs [hunk 10]
```diff
@@ -136,16 +135,16 @@ fn json_set(ctx: &Context, args: Vec<String>) -> RedisResult {
         }
         (None, SetOptions::AlreadyExists) => Ok(RedisValue::Null),
         (None, _) => {
-            let doc = RedisJSON::from_str(&value, &index, format)?;
+            let doc = RedisJSON::from_str(&value, &value_index, format)?;
             if path == "$" {
                 redis_key.set_value(&REDIS_JSON_TYPE, doc)?;
 
-                if let Some(index) = index {
+                if let Some(index) = value_index {
```
Comment (gavrie) [inline src/lib.rs:142]: As above: `if let Some(value_index) = value_index {`

File: src/lib.rs (hunk 9 above)
Comment (gkorland) [reply src/lib.rs:127]: :+1:

File: src/lib.rs (hunk 10 above)
Comment (gkorland) [reply src/lib.rs:142]: :+1:
